tiles_dir : '/tmp/data' #Training/Test dir
tiles_color_normalized_dir : '/media/zw/Elements1/tiles_cn'
model_path : '/home/xisx/tmbpredictor/results/model.pkl'

test_dir : '/home/xisx/data/HE/xiehe/tiles_cn' 

ratio_train : 1  # training set ratio
ratio_test : 0.2  # test set ratio

num_epochs : 50  # epochs for training

use_lmdb : False
load_data_type : 2  # 0:dir  1: lmdb  2: file
k : 5
